{% set version = "2019.1.0" %}

package:
  name: fenics-fiat
  version: {{ version }}

source:
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-{{ version }}.tar.gz
  sha256: 341a1046cbe0f5f2eb26630c2f71f378b0dca51daf9892a54a2ff193970371e9

build:
  number: 40
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - setuptools
    - sympy >=1
test:
  requires:
    - python {{ python_min }}
  imports:
    - FIAT
about:
  home: https://www.fenicsproject.org
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: 'The FInite element Automatic Tabulator FIAT supports generation of arbitrary order instances of the Lagrange elements on lines, triangles, and tetrahedra.'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (https://fenicsproject.org). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: https://fenics.readthedocs.io
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
    - jan-janssen
